creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - age1h4g0q65juvm2m8c4k7whxdyz4uk3yyw0g3d0efv7vycrqapsq4gqqf22yd
        - age19u4v8qduy350073xgzjt0htwnnurxan27a2842y9cujedvk2ddfscrlmw0
